unit test in TDD
Jafarl1/Test-Driven-Development pull request #1
Opened 2023-08-25 21:00 UTC by Jafarl1

2023-08-29 14:26 UTC, elchinimanov commented
qeyd elediklerimi fix et, dersde danışdığımız kimi

2023-08-29 14:26 UTC, elchinimanov requested changes
Please update PR

2023-08-29 19:14 UTC, Jafarl1 commented
Deyishdim :)

2023-09-05 17:18 UTC, elchinimanov commented
unit test in TDD duzgun seslemir. Sadece Test Driven Development olsa daha dogru olar.

2023-09-05 17:22 UTC, elchinimanov approved these changes
Cool 👌

2023-09-19 15:20 UTC, merged